import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "./component/header/page";
import Main from "./component/header/main/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={inter.className}>
        {children}
        <Header />
        <Main/>
      </body>
    </html>
  );
}
